/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * .
 */
export interface EStarClassType { 
    /**
     * The type name of this  transformed enum.
     */
    typeName: string;
    /**
     * The icon name for this resource.
     */
    iconName: string;
    /**
     * The folder name for resources.
     */
    folder: string;
    /**
     * The spectral class.
     */
    spectralClass: string;
    /**
     * The hyper limit in light minutes..
     */
    lightMinutesToHyperLimit: number;
}