/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Coords} from './coords';

/**
 * .
 */
export interface Junction { 
    position: Coords;
    /**
     * All termini of the junction.
     */
    termini: Array<Coords>;
}
