/**
 * BoF REST API
 * Battle for honor interface
 *
 * OpenAPI spec version: 0.1.4
 * Contact: webmaster@batleforhonor.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {NamedThing} from "../../../modules/star-map/external-map-manager/external-map-manager.component";

/**
 * .
 */
export interface Junction { 
    nexus: NamedThing;
    /**
     * All termini of the junction.
     */
    termini: Array<NamedThing>;
}
